# Generated by Django 5.0.3 on 2024-04-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserLastname', models.CharField(max_length=500)),
                ('UserSurname', models.CharField(max_length=500)),
                ('UserAge', models.PositiveIntegerField()),
                ('UserGender', models.CharField(max_length=10)),
                ('UserCity', models.CharField(max_length=500)),
            ],
        ),
    ]
